### ISSUE TITLE
Problem rendering size property of nested immutable map

### ISSUE THREAD

**Issue by hoegrammer** [glenjamin/skin-deep#3]
The component outputs a div containing the size of the `elements` map belonging to `thing`.
The test for this fails despite the console log showing that the value of `size` is being correctly determined by the component. It seems that skin deep is not rendering correctly.

``` javascript
var React = require('react');
var SkinDeep = require('skin-deep');
var Immutable = require('immutable');
var expect = require('chai').expect;

var Component = React.createClass({
  render() {
    var size = this.props.thing.get('elements').size;
    console.log("size: ", size);
    return (<div>{size}</div>);
  }
});

describe('Component', () => {
  it('should show 0 when the thing has no elements', () => {
    var thing = Immutable.Map({
        elements: Immutable.Map(),
    }); 
    var renderedComponent = SkinDeep.shallowRender(
      () => <Component thing = {thing}/>
    );  
    expect(renderedComponent.text()).to.eql('0');
  }); 

  it('should show 2 when the thing has 2 elements', () => {
    var thing = Immutable.Map({
        elements: Immutable.Map({1: "one", 2: "two"}),
    }); 
    var renderedComponent = SkinDeep.shallowRender(
      () => <Component thing = {thing}/>
    );  
    expect(renderedComponent.text()).to.eql('2');
  }); 
});

```

**Comment by glenjamin** [comment]
Ah, I think this is because of an (invalid) assumption about strings vs numbers

**Comment by glenjamin** [comment]
Should be fixed in 771b8f8238

**Comment by hoegrammer** [comment]
I'm still getting a fail on the zero case

      3) Component should show 0 when the thing has no elements:

      AssertionError: expected '' to deeply equal '0'
      + expected - actual

      +0

**Comment by glenjamin** [comment]
Good spot, fixed in 444067edd6b30b36a1da0a37d7c4b706e4b2aad7

Will be released shortly as `v0.1.2`
